name: streamline-controller
services:
  # image autoupdater
  # wud:
  #   image: getwud/wud:${WUD_VERSION:-8.0.1}
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     streamline-network:
  #       aliases:
  #         - wud
  #   environment:
  #     # check for updates every day at 1am
  #     - WUD_WATCHER_LOCAL_CRON=${WUD_CRON_MARK:-0 1 * * *}
  #     # disable auto-updates for all containers by default (except for those with wud.watch=true label deliberately set)
  #     - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false


  controller-backend:
    image: ${CONTROLLER_BACKEND_IMAGE:?}:${CONTROLLER_BACKEND_TAG:?}
    restart: unless-stopped
    networks:
      streamline-network:
        aliases:
          - controller-backend
    volumes:
      - data:/server-data
    secrets:
      - portainer-password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-backend.rule=PathPrefix(`${CONTROLLER_BACKEND_URL_PATH:?}`)"
      - "traefik.http.middlewares.controller-backend-stripprefix.stripprefix.prefixes=${CONTROLLER_BACKEND_URL_PATH:?}"
      - "traefik.http.routers.controller-backend.middlewares=controller-backend-stripprefix"

      ## Following rule is used to properly direct requests to controller.
      ## Controller fetches static files using path like /file.css, without prefix "/admin/api". And requests gets routed to web (due to traefik rules)
      ## So following rule detect when controller requests some static file using Referer header and path that ends with .css, .js, etc.
      ## and route requests back to controller.
      - "traefik.http.routers.controller-backend-referer.rule=HeaderRegexp(`Referer`, `.*://[^/]+${CONTROLLER_BACKEND_URL_PATH}.*`) && PathRegexp(`.*\\.([a-zA-Z0-9]+)$`)"
      - "traefik.http.routers.controller-backend-referer.middlewares=controller-backend-stripprefix"
      - "traefik.http.routers.controller-backend-referer.entrypoints=web"

      # This means the container will be stopped during backup to ensure backup integrity.
      - docker-volume-backup.stop-during-backup=true

    environment:
      - FRONTEGG_ENVIRONMENT=${FRONTEGG_ENVIRONMENT:?}

      - CONTROLLER_BACKEND_URL_PATH=${CONTROLLER_BACKEND_URL_PATH:?}

      - PORTAINER_HOST=portainer  ## same as in portainer/compose.yml
      - PORTAINER_PORT=9000    ## same as in portainer/compose.yml
      - PORTAINER_USER=admin   ## set by installer script
      - PORTAINER_PASSWORD_FILE=/run/secrets/portainer-password  ## file generated by secret 

      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME:-streamline-network}
      - STREAMLINE_VOLUME_NAME=${STREAMLINE_VOLUME_NAME:-streamline-data-${FRONTEGG_ENVIRONMENT:?}}
      - CONTROLLER_STACK_NAME=${CONTROLLER_STACK_NAME:?} ## Pass stack name if it is present

      - MANIFESTS_GIT_REPO_USERNAME=${MANIFESTS_GIT_REPO_USERNAME}
      - MANIFESTS_GIT_REPO_PASSWORD=${MANIFESTS_GIT_REPO_PASSWORD}
      - MANIFESTS_GIT_REPO_SLUG=${MANIFESTS_GIT_REPO_SLUG}
      - SETUP_CF_TOKEN_AT_STARTUP=${SETUP_CF_TOKEN_AT_STARTUP}

  controller-frontend:
    image: ${CONTROLLER_FRONTEND_IMAGE:?}:${CONTROLLER_FRONTEND_TAG:?}
    restart: unless-stopped
    command: --port=80 --backend-host=controller-backend --backend-port=80 --app-path=${STREAMLINE_WEB_URL_PATH:?} --frontegg-env=${FRONTEGG_ENVIRONMENT:?}
    networks:
      - streamline-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-frontend.rule=PathPrefix(`${CONTROLLER_FRONTEND_URL_PATH:?}`)"
      - "traefik.http.middlewares.controller-frontend-stripprefix.stripprefix.prefixes=${CONTROLLER_FRONTEND_URL_PATH:?}"
      - "traefik.http.routers.controller-frontend.middlewares=controller-frontend-stripprefix"

      ## Following rule is used to properly direct requests to controller.
      ## Controller frontend cant properly make requests to it's own web server. 
      ## Instead of making requests to /admin/ui, it makes requests to / and request gets routed to streamline main app web.
      ## Following rule detect when controller frontend tries to make request to it's own web server and route requests to web server..
      - "traefik.http.routers.controller-frontend-referer.rule=HeaderRegexp(`Referer`, `.*://[^/]+${CONTROLLER_FRONTEND_URL_PATH}.*`) && !Path(`${STREAMLINE_WEB_URL_PATH:?}`) && (PathRegexp(`.*\\.([a-zA-Z0-9]+)$`) || PathPrefix(`/api`))" 
      - "traefik.http.routers.controller-frontend-referer.middlewares=controller-frontend-stripprefix"
      - "traefik.http.routers.controller-frontend-referer.entrypoints=web"

      ## Following router is used to redirect requests from /admin to /admin/ui. Just for convenience.
      - "traefik.http.routers.redirect-from-admin.rule=PathRegexp(`^/admin/?$`)"
      - "traefik.http.routers.redirect-from-admin.entrypoints=web"
      - "traefik.http.routers.redirect-from-admin.service=noop@internal"  ## Service is not needed, only redirect
      - "traefik.http.middlewares.redirect-from-admin.redirectregex.regex=^(https?://[^/]+)/admin/?$" ## Any host or port
      - "traefik.http.middlewares.redirect-from-admin.redirectregex.replacement=$${1}${CONTROLLER_FRONTEND_URL_PATH:?}"
      - "traefik.http.routers.redirect-from-admin.middlewares=redirect-from-admin"

secrets:
  portainer-password:
    file: /var/lib/gmdh-streamline-server/.portainer-admin-pwd.txt  ## file created by installer script

networks:
  streamline-network:
    name: ${DOCKER_NETWORK_NAME:-streamline-network} 
    external: true 

volumes:
  data:
    name: ${STREAMLINE_VOLUME_NAME:-streamline-data-${FRONTEGG_ENVIRONMENT:?}}
